service: sls-1t21-capital-conversion-handler

useDotenv: true

frameworkVersion: '2'

package:
  patterns:
    # Includes
    - 'dist/**.js'
    - 'fonts/**'
    # Excludes
    - '!./**.md'
    - '!./**.env*'
    - '!.cache/**'
    - '!.git/**'
    - '!.github/**'
    - '!.npm/**'
    - '!.npm-global/**'
    - '!.pki/**'
    - '!.scannerwork/**'
    - '!coverage/**'
    - '!database/**'
    - '!docker/**'
    - '!docs/**'
    - '!dist/tsconfig.build.tsbuildinfo'
    - '!src/**'
    - '!test/**'
    - '!.eslintrc.js'
    - '!.npmrc'
    - '!.prettier*'
    - '!./tsconfig*.json'
    - '!Jenkinsfile'
    - '!jest.json'
    - '!nest-cli.json'
    - '!run-sonar.sh'
    - '!sonar-project.properties'

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, env:AWS_REGION}
  stage: ${opt:stage, 'local'}
  kmsKeyArn: ${env:KMS_ENV_VARS_ARN}
  deploymentBucket:
    name: ${env:SLS_DEPLOYMENT_BUCKET}
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 5
  stackTags:
    app:environment: ${opt:stage, self:provider.stage}
    app:service: ${self:service}
    app:team: Capital
    app:contact: dl-art-elec-thetransporters@airbus.com
  lambdaHashingVersion: 20201221
  endpointType: private
  iam:
    role:
      statements: # IAM role statements so that services can be accessed in the AWS account
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
          Resource:
            - ${cf:${self:custom.infraStack}.exportBucketArn}
            - ${cf:${self:custom.infraStack}.exportBucketArn}/*
        - Effect: Allow
          Action:
            - kms:Decrypt
          Resource:
            - ${env:KMS_INTEGRATION_KEY_ARN}
        - Effect: Allow # necessary to allow publishing to the encrypted topic
          
        
  logRetentionInDays: 7
  
custom:
  infraStack: sls-1t21-capital-infra-${opt:stage}

functions:
  hello:
    handler: handler.hello
    description: Handler for SVG to TIFF conversion
    memorySize: 4096 # in MB, equivalent to 4GB of heap size to handle possible large SVG file in-memory
    environment:
      FONTCONFIG_PATH: /var/task/fonts
      LOG_LEVELS: ${env:LOG_LEVELS}
      NO_COLOR: true # disable colored logging with Nest.js, which breaks CloudWatch display
      S3_EXPORT_BUCKET_NAME: ${cf:${self:custom.infraStack}.exportBucketName}
      STAGE: ${self:provider.stage}
    events:
      - s3:
          bucket: ${cf:${self:custom.infraStack}.exportBucketName}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - suffix: .svg # Lambda triggers whenever a new file with suffix (.svg) extension is added
    timeout: 600 # 10 minutes
